// Tara Glen v6 entry: scenes + DOM buttons. All content comes from public/world.json (generated by `npm run gen`).
import Phaser from 'phaser';
import './joystick';
import { Swing, Keepy, Putt } from './minigames';
import { G, $ } from './mech/core';
import { World, params } from './v6/world';
import { Room } from './v6/room';
import { UI } from './v6/ui';

// Render resolution: the world is drawn with an integer number of device px per world px (camera zoom 4 on a 3x phone).
// When that number is even we render the canvas at half the device resolution and let CSS (image-rendering: pixelated)
// double it: identical pixels on screen, a quarter of the fill cost. Text in the canvas is then 1.5x instead of 3x.
const DEV = Math.min(window.devicePixelRatio || 1, 3), ZD = Math.max(1, Math.round(Math.min(innerWidth, innerHeight) * DEV / 288));
const DPR = params.has('overview') ? 1 : params.has('fullres') || ZD % 2 || DEV < 2 ? DEV : DEV / 2;
const game = new Phaser.Game({
  type: Phaser.AUTO, parent: 'game', backgroundColor: '#000000', pixelArt: true, roundPixels: true,
  scale: { mode: Phaser.Scale.NONE, width: innerWidth * DPR, height: innerHeight * DPR, zoom: 1 / DPR },
  physics: { default: 'arcade', arcade: { debug: params.has('physics') } },
  scene: [World, Room, Swing, Keepy, Putt, UI],
});
const active = () => (game.scene.isActive('Room') ? game.scene.getScene('Room') : game.scene.getScene('World')) as any;
const btn = (id: string, f: () => void) => $(id).addEventListener('pointerdown', (e) => { e.stopPropagation(); e.preventDefault(); f(); });
btn('fire', () => active().fire());
btn('dash', () => active().dash());
btn('prompt', () => !G.paused && active().interact());
addEventListener('keydown', (e) => { if ((e.key === ' ' || e.key === 'Enter') && !G.paused) active().interact?.(); });
addEventListener('resize', () => game.scale.resize(innerWidth * DPR, innerHeight * DPR));
