// Tara Glen v6 entry: scenes + DOM buttons. All content comes from public/world.json (generated by `npm run gen`).
import Phaser from 'phaser';
import './joystick';
import { Swing, Keepy, Putt } from './minigames';
import { G, $ } from './mech/core';
import { World, params } from './v6/world';
import { Room } from './v6/room';
import { UI } from './v6/ui';

const DPR = params.has('overview') ? 1 : Math.min(window.devicePixelRatio || 1, 3);
const game = new Phaser.Game({
  type: Phaser.AUTO, parent: 'game', backgroundColor: '#000000', pixelArt: true, roundPixels: true,
  scale: { mode: Phaser.Scale.NONE, width: innerWidth * DPR, height: innerHeight * DPR, zoom: 1 / DPR },
  physics: { default: 'arcade', arcade: { debug: params.has('physics') } },
  scene: [World, Room, Swing, Keepy, Putt, UI],
});
const active = () => (game.scene.isActive('Room') ? game.scene.getScene('Room') : game.scene.getScene('World')) as any;
const btn = (id: string, f: () => void) => $(id).addEventListener('pointerdown', (e) => { e.stopPropagation(); e.preventDefault(); f(); });
btn('fire', () => active().fire());
btn('dash', () => active().dash());
btn('prompt', () => !G.paused && active().interact());
addEventListener('keydown', (e) => { if ((e.key === ' ' || e.key === 'Enter') && !G.paused) active().interact?.(); });
addEventListener('resize', () => game.scale.resize(innerWidth * DPR, innerHeight * DPR));
